run:
  timeout: 10m
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: run-script-service
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: main\.go
      linters:
        - gocyclo # Main function complexity is acceptable
        - depguard # Main package needs to import service packages
    - path: service/config\.go
      linters:
        - gosec # Config file reading is expected behavior
        - revive # Allow ServiceConfig name for clarity
    - path: service/executor\.go
      linters:
        - gosec # Script execution is the core functionality

  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # gosec: These security warnings are expected in this service context
    - "G304: Potential file inclusion via variable" # Config file reading is intended
    - "G204: Subprocess launched with a potential tainted input" # Script execution is the core feature

  max-issues-per-linter: 0
  max-same-issues: 0
