run:
  timeout: 5m
  tests: true

linters-settings:
  dupl:
    threshold: 100
  goimports:
    local-prefixes: run-script-service

linters:
  disable-all: true
  enable:
    # Core linters for code correctness
    - gofmt         # Code formatting
    - goimports     # Import formatting and organization
    - typecheck     # Type checking
    - dupl          # Duplicate code detection (this was the original issue)

    # These can be enabled gradually:
    # - errcheck    # Error handling
    # - govet       # Go vet checks
    # - ineffassign # Unused assignments
    # - unused      # Unused code

# Minimal configuration for gradual adoption
# We'll add more strict rules as we fix existing issues

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
