name: CI - Backend & Frontend

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install Go tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.1

    - name: Install frontend dependencies
      run: |
        cd web/frontend && pnpm install --frozen-lockfile

    - name: Run frontend tests
      run: make test-frontend

    - name: Build frontend
      run: make build-frontend

    - name: Run backend tests and checks
      run: make format lint test

    - name: Build complete application
      run: make build-all

    - name: Generate coverage report
      run: make coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        fail_ci_if_error: false
